version: "3"
services:
  tcc_loader:
    image: tcc_loader
    stdin_open: true
    tty: true
    entrypoint: sh # Debug mode
    # entrypoint: "sanic"
    # command: ["main:app", "--host=0.0.0.0", "--port=1997", "--workers=1", "-r", "-d"]
    ports:
      - "1997:1997"
    volumes:
      - ./tcc_loader:/sanic
    networks:
      - tcc_egide
  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql
    environment:
      POSTGRES_USER: arthur
      POSTGRES_PASSWORD: egide
      POSTGRES_DB: db
    networks:
      - tcc_egide
networks:
  tcc_egide:
    name: tcc_egide
    external: true